### PR TITLE
[PR] refactoring + pyTest

### PR DESCRIPTION
**Pull request by rapidrabbit76**
# Summary

refactoring 

# Work

- tensorflow 2.7.1 support 
- wandb logger support
- pytest test code 
- github action integration
- refactoring

### CODE REVIEW

**Comment by rapidrabbit76** [comment]
thanos snap

**Review by rapidrabbit76 — COMMENTED** [review]
This branch cannot be rebased due to conflicts

**Comment by Sam2much96** [comment]
Glad you're active dev. I truely really appreciate your code.

**Comment by rapidrabbit76** [comment]
oh .. I did not know anyone was interested in my project. haha

I'll be uploading a serving backend soon.

**Pull request merged**
